peer:
  id: peer0.client.etsi.com
  networkId: dev
  address: peer0.client.etsi.com:9051
  localMspId: ClientMSP

  tls:
    enabled: true
    cert:
      file: /etc/hyperledger/fabric/tls/server.crt
    key:
      file: /etc/hyperledger/fabric/tls/server.key
    rootcert:
      file: /etc/hyperledger/fabric/tls/ca.crt

  endorsement:
    plugin: escc
    pluginMapping:
      "": escc

  deliveryclient:
    reconnectTotalTimeThreshold: 3600s
    connTimeout: 2s
    reConnectBackoffThreshold: 5.0s

ledger:
  blockchain:
    rootDir: /var/hyperledger/production
  snapshots:
    rootDir: /var/hyperledger/production/snapshots

fileSystemPath: /var/hyperledger/production

mspConfigPath: /etc/hyperledger/fabric/msp

msp:
  type: bccsp
  bccsp:
    Default: SW
    SW:
      Hash: SHA2
      Security: 256

peer.gossip:
  bootstrap: peer0.client.etsi.com:9051
  useLeaderElection: true
  orgLeader: false
  maxBlockCountToStore: 100

peer.deliveryclient.addressOverrides:
  - from: localhost:7050
    to: orderer1.etsi.com:7050
    caCertsFile: /etc/hyperledger/fabric/tls/ca.crt

state:
  database: CouchDB
  couchDBConfig:
    address: couchdb0:5984
    username: "admin"
    password: "adminpw"
    maxRetries: 3
    requestTimeout: 35s

logging:
  level: DEBUG
  gossip: warning
  cauthdsl: warning
  policy: warning
  grpc: error
