# peer0.seller.core.yaml
peer:
  id: peer0.seller.etsi.com
  networkId: dev
  address: peer0.seller.etsi.com:8051
  localMspId: SellerMSP

  # Configuración del TLS
  tls:
    enabled: true
    cert:
      file: /home/daniel/TFGP/crypto-config/peerOrganizations/seller.etsi.com/peers/peer0.seller.etsi.com/tls/server.crt
    key:
      file: /home/daniel/TFGP/crypto-config/peerOrganizations/seller.etsi.com/peers/peer0.seller.etsi.com/tls/server.key
    rootcert:
      file: /home/daniel/TFGP/crypto-config/peerOrganizations/seller.etsi.com/peers/peer0.seller.etsi.com/tls/ca.crt

  # Configuración de los Endorsement Plugins
  endorsement:
    plugin: escc
    pluginMapping:
      "": escc

  # Configuración del Event Service
  deliveryclient:
    reconnectTotalTimeThreshold: 3600s
    connTimeout: 2s
    reConnectBackoffThreshold: 5.0s

# Configuración del Peer en cuanto a los libros contables
ledger:
  blockchain:
    pvtdataStore:
      subdir: "ledger"

# Configuración del File System Path
fileSystemPath: /var/hyperledger/production/seller

mspConfigPath: /home/daniel/TFGP/crypto-config/peerOrganizations/seller.etsi.com/peers/peer0.seller.etsi.com/msp

# Configuración de la variable MSP
msp:
  type: bccsp
  bccsp:
    Default: SW
    SW:
      Hash: SHA2
      Security: 256

# Habilitar la comunicación gossip
peer.gossip:
  bootstrap: peer0.seller.etsi.com:8051
  useLeaderElection: true
  orgLeader: false
  maxBlockCountToStore: 100

# Direcciones de Orderers conocidos
peer.deliveryclient.addressOverrides:
  - from: localhost:7050
    to: orderer1.etsi.com:7050
    caCertsFile: /home/daniel/TFGP/crypto-config/ordererOrganizations/etsi.com/orderers/orderer1.etsi.com/tls/ca.crt

# Configuración para la base de datos de nivel de mundo
state:
  database: CouchDB
  couchDBConfig:
    address: couchdb0:5984
    username: "admin"
    password: "adminpw"
    maxRetries: 3
    requestTimeout: 35s

logging:
  level: info
  gossip: warning
  cauthdsl: warning
  policy: warning
  grpc: error
