version: '2.2'

networks:
  etsi-network:
    driver: bridge

services:
  orderer1.etsi.com:
    container_name: orderer1.etsi.com
    image: hyperledger/fabric-orderer:2.2.0
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=/var/hyperledger/orderer/tls/ca.crt
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
    ports:
      - 7050:7050
    volumes:
      - ../crypto-config/ordererOrganizations/etsi.com/orderers/orderer1.etsi.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/etsi.com/orderers/orderer1.etsi.com/tls:/var/hyperledger/orderer/tls
      - ../config/orderer.yaml:/etc/hyperledger/fabric/orderer.yaml
      - ../channel-artifacts/genesis.block:/etc/hyperledger/fabric/genesisblock
    networks:
      - etsi-network

  orderer2.etsi.com:
    container_name: orderer2.etsi.com
    image: hyperledger/fabric-orderer:2.2.0
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=8050
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=/var/hyperledger/orderer/tls/ca.crt
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
    ports:
      - 8050:8050
    volumes:
      - ../crypto-config/ordererOrganizations/etsi.com/orderers/orderer2.etsi.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/etsi.com/orderers/orderer2.etsi.com/tls:/var/hyperledger/orderer/tls
      - ../config/orderer.yaml:/etc/hyperledger/fabric/orderer.yaml
      - ../channel-artifacts/genesis.block:/etc/hyperledger/fabric/genesisblock
    networks:
      - etsi-network

  orderer3.etsi.com:
    container_name: orderer3.etsi.com
    image: hyperledger/fabric-orderer:2.2.0
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=9050
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=/var/hyperledger/orderer/tls/ca.crt
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
    ports:
      - 9050:9050
    volumes:
      - ../crypto-config/ordererOrganizations/etsi.com/orderers/orderer3.etsi.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/etsi.com/orderers/orderer3.etsi.com/tls:/var/hyperledger/orderer/tls
      - ../config/orderer.yaml:/etc/hyperledger/fabric/orderer.yaml
      - ../channel-artifacts/genesis.block:/etc/hyperledger/fabric/genesisblock
    networks:
      - etsi-network

  peer0.buyer.etsi.com:
    container_name: peer0.buyer.etsi.com
    image: hyperledger/fabric-peer:2.2.0
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=etsi-network
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE:/etc/hyperledger/fabric/tls/ca.crt:/etc/hyperledger/fabric/tls/orderer-tlsca.crt
      - CORE_PEER_ID=peer0.buyer.etsi.com
      - CORE_PEER_ADDRESS=peer0.buyer.etsi.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.buyer.etsi.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_LOCALMSPID=BuyerMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    volumes:
      - ../crypto-config/peerOrganizations/buyer.etsi.com/peers/peer0.buyer.etsi.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/buyer.etsi.com/peers/peer0.buyer.etsi.com/tls:/etc/hyperledger/fabric/tls
      - ../config/peer-configs/peer0.buyer.core.yaml:/etc/hyperledger/fabric/core.yaml
      - /home/daniel/TFGP/ledgersData:/var/hyperledger/production
      - /var/run/:/host/var/run/
    ports:
      - "7051:7051"
    networks:
      - etsi-network

  peer0.seller.etsi.com:
    container_name: peer0.seller.etsi.com
    image: hyperledger/fabric-peer:2.2.0
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=etsi-network
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE:/etc/hyperledger/fabric/tls/ca.crt:/etc/hyperledger/fabric/tls/orderer-tlsca.crt
      - CORE_PEER_ID=peer0.seller.etsi.com
      - CORE_PEER_ADDRESS=peer0.seller.etsi.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer0.seller.etsi.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_LOCALMSPID=SellerMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    volumes:
      - ../crypto-config/peerOrganizations/seller.etsi.com/peers/peer0.seller.etsi.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/seller.etsi.com/peers/peer0.seller.etsi.com/tls:/etc/hyperledger/fabric/tls
      - ../config/peer-configs/peer0.seller.core.yaml:/etc/hyperledger/fabric/core.yaml
      - /home/daniel/TFGP/ledgersData:/var/hyperledger/production
      - /var/run/:/host/var/run/
    ports:
      - "8051:8051"
    networks:
      - etsi-network

  peer0.client.etsi.com:
    container_name: peer0.client.etsi.com
    image: hyperledger/fabric-peer:2.2.0
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=etsi-network
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE:/etc/hyperledger/fabric/tls/ca.crt:/etc/hyperledger/fabric/tls/orderer-tlsca.crt
      - CORE_PEER_ID=peer0.client.etsi.com
      - CORE_PEER_ADDRESS=peer0.client.etsi.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.client.etsi.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_LOCALMSPID=ClientMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    volumes:
      - ../crypto-config/peerOrganizations/client.etsi.com/peers/peer0.client.etsi.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/client.etsi.com/peers/peer0.client.etsi.com/tls:/etc/hyperledger/fabric/tls
      - ../config/peer-configs/peer0.client.core.yaml:/etc/hyperledger/fabric/core.yaml
      - /home/daniel/TFGP/ledgersData:/var/hyperledger/production
      - /var/run/:/host/var/run/
    ports:
      - "9051:9051"
    networks:
      - etsi-network


  couchdb0:
    container_name: couchdb0
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "5984:5984"
    networks:
      - etsi-network

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.2.0
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.buyer.etsi.com:7051
      - CORE_PEER_LOCALMSPID=BuyerMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - ../crypto-config:/etc/hyperledger/fabric/crypto-config
      - ../channel-artifacts:/etc/hyperledger/fabric/channel-artifacts
      - ../chaincode:/opt/gopath/src/github.com/
      - ../crypto-config/peerOrganizations/buyer.etsi.com/peers/peer0.buyer.etsi.com/tls:/etc/hyperledger/fabric/tls
      - ../crypto-config/peerOrganizations/buyer.etsi.com/users/Admin@buyer.etsi.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/ordererOrganizations/etsi.com/orderers:/etc/hyperledger/fabric/orderer-tls      
    networks:
      - etsi-network
