OrdererOrgs:
  - Name: etsi
    Domain: etsi.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer1
      - Hostname: orderer2
      - Hostname: orderer3
    CA:
      Country: US
      Province: California
      Locality: San Francisco
      OrganizationalUnit: Orderer
      StreetAddress: 1 Main Street
      PostalCode: 94111

PeerOrgs:
  - Name: buyer
    Domain: buyer.etsi.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 2
    CA:
      Country: US
      Province: California
      Locality: San Francisco
      OrganizationalUnit: Buyer
      StreetAddress: 2 Buyer Lane
      PostalCode: 94111

  - Name: seller
    Domain: seller.etsi.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 2
    CA:
      Country: US
      Province: California
      Locality: San Francisco
      OrganizationalUnit: Seller
      StreetAddress: 3 Seller Drive
      PostalCode: 94111

  - Name: client
    Domain: client.etsi.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 2
    CA:
      Country: US
      Province: California
      Locality: San Francisco
      OrganizationalUnit: Client
      StreetAddress: 4 Client Avenue
      PostalCode: 94111
